service: ${env:APP_NAME}
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-log-retention
  #
  # Uncomment below to enable nested stacks on CloudFormation
  # See https://reflex-media.github.io/lesgo-docs/0.7.7/prologue/release-notes/#cloudformation-nested-stack-support
  #
  # - serverless-plugin-split-stacks
  #
  # Uncomment below to slow down deployment process.
  # See https://reflex-media.github.io/lesgo-docs/0.7.7/prologue/release-notes/#chaining-deployment
  #
  # - serverless-dependson-plugin

package:
  individually: true

useDotenv: true
configValidationMode: error

provider:
  name: aws
  architecture: arm64
  runtime: nodejs12.x
  memorySize: 128
  timeout: 5
  stackName: ${self:service}-${self:provider.stage}
  apiName: ${self:provider.stackName}
  stage: ${opt:stage, 'local'}
  profile: ${env:AWS_ACCOUNT_PROFILE}
  region: ${opt:region, env:AWS_ACCOUNT_REGION}
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 100
  httpApi:
    cors: true
  #
  # Uncomment to deploy app within a VPC
  #
  # vpc:
  #   securityGroupIds:
  #     - ${env:AWS_VPC_SECURITY_GROUP_ID}
  #   subnetIds:
  #     - ${env:AWS_VPC_SUBNET_1_ID}
  #     - ${env:AWS_VPC_SUBNET_2_ID}
  #     - ${env:AWS_VPC_SUBNET_3_ID}
  #     - ${env:AWS_VPC_SUBNET_4_ID}
  stackTags:
    SITE: ${self:service}
    PRODUCT: ${self:service}
    STAGE: ${self:provider.stage}
    datadog: monitored
    service: ${env:APP_NAME}
    env: ${self:provider.stage}
  #
  # Add additional permission for your app here
  #
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: '*'

custom:
  path:
    app: src
    functions: config/functions
    resources: config/resources
  serverless-offline:
    port: 8888
    ignoreJWTSignature: true
  logRetentionInDays: 7
  dotenv:
    basePath: config/environments/
  #
  # Config for serverless-plugin-split-stacks
  #
  # splitStacks:
  #   perFunction: false
  #   perType: true
  #   perGroupFunction: false
  #
  # Config for serverless-dependson-plugin
  #
  # dependsOn:
  #   enabled: true
  #   chains: 15

#
# Add functions here
#
functions:
  - ${file(${self:custom.path.functions}/utils.yml)}

#
# Add resources here
#
resources:
  # - ${file(${self:custom.path.resources}/sample-resource.yml)}
